server:
  port: 9113
dubbo:
  application:
    name: online-school-service #应用名称  
spring:
  profiles: 
    active: test #生产环境
  aop:
    auto: true # Add @EnableAspectJAutoProxy.
    proxy-target-class: true # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
logging:
  path: /gomeo2o/logs/${dubbo.application.name} #输出到磁盘目录




